import { buildWindowsAgentHookPostCommand } from '../agent-hooks/installer-utils'
import {
  buildPosixHookPayloadCapture,
  buildWindowsHookEnvironmentGuardLines,
  buildWindowsHookStdinDrainEpilogue
} from '../agent-hooks/hook-stdin-contract'

export type CommandCodeManagedScriptTarget = 'local' | 'posix'

export function buildCommandCodeManagedScript(
  target: CommandCodeManagedScriptTarget = 'local'
): string {
  if (target === 'local' && process.platform === 'win32') {
    return [
      '@echo off',
      'setlocal',
      'if "%BOTMUX_AGENT_HOOK_PORT%"=="" if defined BOTMUX_AGENT_HOOK_ENDPOINT if exist "%BOTMUX_AGENT_HOOK_ENDPOINT%" call "%BOTMUX_AGENT_HOOK_ENDPOINT%" 2>nul',
      'if "%BOTMUX_AGENT_HOOK_TOKEN%"=="" if not "%BOTMUX_AGENT_HOOK_PORT%"=="" call :sourceEndpointByPort',
      ...buildWindowsHookEnvironmentGuardLines(),
      buildWindowsAgentHookPostCommand('command-code'),
      'exit /b 0',
      ':sourceEndpointByPort',
      'if not defined APPDATA exit /b 0',
      'if exist "%APPDATA%\\botmux-desktop-dev\\agent-hooks" for /r "%APPDATA%\\botmux-desktop-dev\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'if "%BOTMUX_AGENT_HOOK_TOKEN%"=="" if exist "%APPDATA%\\botmux\\agent-hooks" for /r "%APPDATA%\\botmux\\agent-hooks" %%F in (endpoint.cmd) do call :maybeSourceEndpoint "%%~fF"',
      'exit /b 0',
      ':maybeSourceEndpoint',
      'if not "%BOTMUX_AGENT_HOOK_TOKEN%"=="" exit /b 0',
      'for /f "tokens=2 delims==" %%P in (\'findstr /b /c:"set BOTMUX_AGENT_HOOK_PORT=" "%~1" 2^>nul\') do if "%%P"=="%BOTMUX_AGENT_HOOK_PORT%" call "%~1" 2>nul',
      'exit /b 0',
      ...buildWindowsHookStdinDrainEpilogue(),
      ''
    ].join('\r\n')
  }

  return [
    '#!/bin/sh',
    ...buildPosixHookPayloadCapture(),
    '__botmux_read_ancestor_var() {',
    '  __botmux_name="$1"',
    '  __botmux_pid="${PPID:-}"',
    '  while [ -n "$__botmux_pid" ] && [ "$__botmux_pid" != "0" ] && [ "$__botmux_pid" != "1" ]; do',
    '    __botmux_value=""',
    '    if [ -r "/proc/$__botmux_pid/environ" ]; then',
    '      __botmux_value=$(tr "\\000" "\\n" < "/proc/$__botmux_pid/environ" 2>/dev/null | sed -n "s/^${__botmux_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -z "$__botmux_value" ]; then',
    '      __botmux_value=$(ps eww -p "$__botmux_pid" -o command= 2>/dev/null | tr " " "\\n" | sed -n "s/^${__botmux_name}=//p" | head -n 1)',
    '    fi',
    '    if [ -n "$__botmux_value" ]; then',
    '      printf "%s\\n" "$__botmux_value"',
    '      return 0',
    '    fi',
    '    __botmux_pid=$(ps -o ppid= -p "$__botmux_pid" 2>/dev/null | tr -d " ")',
    '  done',
    '  return 1',
    '}',
    '__botmux_fill_from_ancestor() {',
    '  __botmux_name="$1"',
    '  case "$__botmux_name" in',
    '    BOTMUX_AGENT_HOOK_ENDPOINT) [ -z "${BOTMUX_AGENT_HOOK_ENDPOINT:-}" ] || return 0 ;;',
    '    BOTMUX_AGENT_HOOK_PORT) [ -z "${BOTMUX_AGENT_HOOK_PORT:-}" ] || return 0 ;;',
    '    BOTMUX_AGENT_HOOK_TOKEN) [ -z "${BOTMUX_AGENT_HOOK_TOKEN:-}" ] || return 0 ;;',
    '    BOTMUX_AGENT_HOOK_ENV) [ -z "${BOTMUX_AGENT_HOOK_ENV:-}" ] || return 0 ;;',
    '    BOTMUX_AGENT_HOOK_VERSION) [ -z "${BOTMUX_AGENT_HOOK_VERSION:-}" ] || return 0 ;;',
    '    BOTMUX_PANE_KEY) [ -z "${BOTMUX_PANE_KEY:-}" ] || return 0 ;;',
    '    BOTMUX_TAB_ID) [ -z "${BOTMUX_TAB_ID:-}" ] || return 0 ;;',
    '    BOTMUX_WORKTREE_ID) [ -z "${BOTMUX_WORKTREE_ID:-}" ] || return 0 ;;',
    '    BOTMUX_AGENT_LAUNCH_TOKEN) [ -z "${BOTMUX_AGENT_LAUNCH_TOKEN:-}" ] || return 0 ;;',
    '    *) return 0 ;;',
    '  esac',
    '  __botmux_value=$(__botmux_read_ancestor_var "$__botmux_name") || return 0',
    '  [ -n "$__botmux_value" ] && export "$__botmux_name=$__botmux_value"',
    '}',
    '__botmux_endpoint_value() {',
    '  __botmux_endpoint_name="$1"',
    '  __botmux_endpoint_path="$2"',
    '  sed -n "s/^${__botmux_endpoint_name}=//p" "$__botmux_endpoint_path" 2>/dev/null | head -n 1',
    '}',
    '__botmux_fill_from_endpoint_file() {',
    '  __botmux_endpoint_path="$1"',
    '  [ -r "$__botmux_endpoint_path" ] || return 0',
    '  __botmux_endpoint_port=$(__botmux_endpoint_value BOTMUX_AGENT_HOOK_PORT "$__botmux_endpoint_path")',
    '  if [ -n "${BOTMUX_AGENT_HOOK_PORT:-}" ] && [ -n "$__botmux_endpoint_port" ] && [ "$__botmux_endpoint_port" != "$BOTMUX_AGENT_HOOK_PORT" ]; then',
    '    return 0',
    '  fi',
    '  for __botmux_endpoint_name in BOTMUX_AGENT_HOOK_PORT BOTMUX_AGENT_HOOK_TOKEN BOTMUX_AGENT_HOOK_ENV BOTMUX_AGENT_HOOK_VERSION; do',
    '    eval "__botmux_current=\\${$__botmux_endpoint_name:-}"',
    '    [ -z "$__botmux_current" ] || continue',
    '    __botmux_endpoint_value=$(__botmux_endpoint_value "$__botmux_endpoint_name" "$__botmux_endpoint_path")',
    '    [ -n "$__botmux_endpoint_value" ] && export "$__botmux_endpoint_name=$__botmux_endpoint_value"',
    '  done',
    '}',
    '# Why: Command Code sanitizes hook subprocess env. The parent TUI process',
    '# still has Botmux pane/hook metadata, so recover it before posting.',
    'for __botmux_name in BOTMUX_AGENT_HOOK_ENDPOINT BOTMUX_AGENT_HOOK_PORT BOTMUX_AGENT_HOOK_TOKEN BOTMUX_AGENT_HOOK_ENV BOTMUX_AGENT_HOOK_VERSION BOTMUX_PANE_KEY BOTMUX_TAB_ID BOTMUX_WORKTREE_ID BOTMUX_AGENT_LAUNCH_TOKEN; do',
    '  __botmux_fill_from_ancestor "$__botmux_name"',
    'done',
    'if [ -n "$BOTMUX_AGENT_HOOK_ENDPOINT" ] && [ -r "$BOTMUX_AGENT_HOOK_ENDPOINT" ]; then',
    '  __botmux_fill_from_endpoint_file "$BOTMUX_AGENT_HOOK_ENDPOINT"',
    'fi',
    '# Why: Command Code strips TOKEN-like env vars before invoking hooks. If',
    '# BOTMUX_AGENT_HOOK_ENDPOINT was not exported into this PTY, recover the',
    '# matching endpoint file by the unstripped loopback port.',
    'if [ -z "$BOTMUX_AGENT_HOOK_TOKEN" ] && [ -n "$BOTMUX_AGENT_HOOK_PORT" ]; then',
    '  for endpoint in \\',
    '    "$HOME/Library/Application Support/botmux-desktop-dev/agent-hooks"/*/endpoint.env \\',
    '    "$HOME/Library/Application Support/botmux-desktop-dev/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/botmux-desktop-dev/agent-hooks"/*/endpoint.env \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/botmux-desktop-dev/agent-hooks/endpoint.env" \\',
    '    "$HOME/Library/Application Support/botmux/agent-hooks/endpoint.env" \\',
    '    "${XDG_CONFIG_HOME:-$HOME/.config}/botmux/agent-hooks/endpoint.env"; do',
    '    [ -r "$endpoint" ] || continue',
    '    endpoint_port=$(sed -n "s/^BOTMUX_AGENT_HOOK_PORT=//p" "$endpoint" | head -n 1)',
    '    if [ "$endpoint_port" = "$BOTMUX_AGENT_HOOK_PORT" ]; then',
    '      __botmux_fill_from_endpoint_file "$endpoint"',
    '      break',
    '    fi',
    '  done',
    'fi',
    'if [ -z "$BOTMUX_AGENT_HOOK_PORT" ] || [ -z "$BOTMUX_AGENT_HOOK_TOKEN" ] || [ -z "$BOTMUX_PANE_KEY" ]; then',
    '  exit 0',
    'fi',
    // Timeout caps best-effort hook posts if the local listener stalls.
    // Why: pipe payload to curl's stdin (`payload@-`) instead of an inline
    // `payload=$VALUE` arg, so tens-of-KB tool output stays off the curl
    // command line (EDR command-line false positives). Wire body is identical.
    'printf \'%s\' "$payload" | curl -sS -X POST "http://127.0.0.1:${BOTMUX_AGENT_HOOK_PORT}/hook/command-code" \\',
    '  --connect-timeout 0.5 --max-time 1.5 \\',
    '  -H "Content-Type: application/x-www-form-urlencoded" \\',
    '  -H "X-Botmux-Agent-Hook-Token: ${BOTMUX_AGENT_HOOK_TOKEN}" \\',
    '  --data-urlencode "paneKey=${BOTMUX_PANE_KEY}" \\',
    '  --data-urlencode "tabId=${BOTMUX_TAB_ID}" \\',
    '  --data-urlencode "launchToken=${BOTMUX_AGENT_LAUNCH_TOKEN}" \\',
    '  --data-urlencode "worktreeId=${BOTMUX_WORKTREE_ID}" \\',
    '  --data-urlencode "env=${BOTMUX_AGENT_HOOK_ENV}" \\',
    '  --data-urlencode "version=${BOTMUX_AGENT_HOOK_VERSION}" \\',
    '  --data-urlencode "payload@-" >/dev/null 2>&1 || true',
    'exit 0',
    ''
  ].join('\n')
}
