/**
 * Extracts and manipulates dynamic markers from user messages or system prompts.
 * Used for both synthetic responses and fixture parameterization.
 */

// Common patterns for markers generated by E2E test suites
const MARKER_PATTERNS = [
  // ACK-e2e-xxx-123456789
  /ACK-(?:e2e-[a-zA-Z0-9_\-]+)/,
  // CODEX_E2E_MARKER_123456789
  /CODEX_E2E_MARKER_\d+/,
  // e2e-xxx-123456789
  /e2e-[a-zA-Z0-9_\-]+-\d+/,
  // General quoted marker: 请在最终回复中原样包含 ([^\s"']+)
  /请在最终回复中原样包含\s+([A-Za-z0-9_\-]+)/,
  // 请立刻调用 botmux send 在本话题里回复一行内容："([^"]+)"
  /请立刻调用\s+botmux\s+send\s+在本话题里回复一行内容：[“"]([A-Za-z0-9_\-.:#@ ]+)[”"]/,
];

/**
 * Scan all text in the conversation history or prompt to locate any dynamic marker.
 */
export function extractMarker(text: string): string | null {
  for (const pattern of MARKER_PATTERNS) {
    const match = text.match(pattern);
    if (match) {
      // If there's a capture group, return it; otherwise the full match
      return match[1] ?? match[0];
    }
  }
  return null;
}

/**
 * Scan deep within message payloads (array of strings / objects) to extract the user's latest marker.
 */
export function extractMarkerFromMessages(messages: unknown[]): string | null {
  if (!Array.isArray(messages)) return null;

  // Search backwards starting from the latest messages
  for (let i = messages.length - 1; i >= 0; i--) {
    const msg = messages[i] as { content?: unknown; role?: string };
    if (!msg) continue;

    if (typeof msg.content === 'string') {
      const marker = extractMarker(msg.content);
      if (marker) return marker;
    } else if (Array.isArray(msg.content)) {
      for (const block of msg.content) {
        if (typeof block === 'string') {
          const marker = extractMarker(block);
          if (marker) return marker;
        } else if (
          block &&
          typeof block === 'object' &&
          'text' in block &&
          typeof (block as { text: unknown }).text === 'string'
        ) {
          const marker = extractMarker((block as { text: string }).text);
          if (marker) return marker;
        }
      }
    }
  }

  return null;
}

/**
 * Generate a safe, quote-escaped `botmux send` bash command to reply to the user.
 * Wraps content in single quotes with standard shell escaping to prevent command injection.
 */
export function buildBotmuxSendCommand(content: string, mentionBack = true): string {
  const sanitized = content.replace(/'/g, "'\\''");
  const mentionFlag = mentionBack ? '--mention-back' : '--no-mention';
  return `botmux send ${mentionFlag} '${sanitized}'`;
}
